/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ClinicalTrialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "grantConsent"
      | "hospital"
      | "patientConsent"
      | "revokeConsent"
      | "uploadData"
      | "viewData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsentGranted"
      | "ConsentRevoked"
      | "DataAccess"
      | "DataUploaded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "grantConsent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hospital", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientConsent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uploadData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewData",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hospital", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uploadData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewData", data: BytesLike): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataAccessEvent {
  export type InputTuple = [
    patient: AddressLike,
    accessor: AddressLike,
    purpose: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    accessor: string,
    purpose: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    accessor: string;
    purpose: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataUploadedEvent {
  export type InputTuple = [
    patient: AddressLike,
    dataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClinicalTrialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ClinicalTrialRegistry;
  waitForDeployment(): Promise<this>;

  interface: ClinicalTrialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  grantConsent: TypedContractMethod<[], [void], "nonpayable">;

  hospital: TypedContractMethod<[], [string], "view">;

  patientConsent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  revokeConsent: TypedContractMethod<[], [void], "nonpayable">;

  uploadData: TypedContractMethod<[dataHash: BytesLike], [void], "nonpayable">;

  viewData: TypedContractMethod<
    [patient: AddressLike, purpose: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hospital"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientConsent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uploadData"
  ): TypedContractMethod<[dataHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "viewData"
  ): TypedContractMethod<
    [patient: AddressLike, purpose: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DataAccess"
  ): TypedContractEvent<
    DataAccessEvent.InputTuple,
    DataAccessEvent.OutputTuple,
    DataAccessEvent.OutputObject
  >;
  getEvent(
    key: "DataUploaded"
  ): TypedContractEvent<
    DataUploadedEvent.InputTuple,
    DataUploadedEvent.OutputTuple,
    DataUploadedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(address,uint256)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(address,uint256)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;

    "DataAccess(address,address,string,uint256)": TypedContractEvent<
      DataAccessEvent.InputTuple,
      DataAccessEvent.OutputTuple,
      DataAccessEvent.OutputObject
    >;
    DataAccess: TypedContractEvent<
      DataAccessEvent.InputTuple,
      DataAccessEvent.OutputTuple,
      DataAccessEvent.OutputObject
    >;

    "DataUploaded(address,bytes32,uint256)": TypedContractEvent<
      DataUploadedEvent.InputTuple,
      DataUploadedEvent.OutputTuple,
      DataUploadedEvent.OutputObject
    >;
    DataUploaded: TypedContractEvent<
      DataUploadedEvent.InputTuple,
      DataUploadedEvent.OutputTuple,
      DataUploadedEvent.OutputObject
    >;
  };
}
