/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClinicalTrialRegistry } from "./ClinicalTrialRegistry";
export type { PatientHospitalRegistry } from "./PatientHospitalRegistry";
export * as factories from "./factories";
export { ClinicalTrialRegistry__factory } from "./factories/ClinicalTrialRegistry__factory";
export { PatientHospitalRegistry__factory } from "./factories/PatientHospitalRegistry__factory";
