/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClinicalTrialRegistry__factory } from "./ClinicalTrialRegistry__factory";
export { PatientHospitalRegistry__factory } from "./PatientHospitalRegistry__factory";
